# Data Input and Output

## HTML input

In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_html('https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/')

In [26]:
df[0]

,Bank NameBank,CityCity,StateSt,CertCert,Acquiring InstitutionAI,Closing DateClosing,FundFund
0,Almena State Bank,Almena,KS,15426,Equity Bank,"October 23, 2020",10538
1,First City Bank of Florida,Fort Walton Beach,FL,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
2,The First State Bank,Barboursville,WV,14361,"MVB Bank, Inc.","April 3, 2020",10536
3,Ericson State Bank,Ericson,NE,18265,Farmers and Merchants Bank,"February 14, 2020",10535
4,City National Bank of New Jersey,Newark,NJ,21111,Industrial Bank,"November 1, 2019",10534
5,Resolute Bank,Maumee,OH,58317,Buckeye State Bank,"October 25, 2019",10533
6,Louisa Community Bank,Louisa,KY,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
7,The Enloe State Bank,Cooper,TX,10716,"Legend Bank, N. A.","May 31, 2019",10531
8,Washington Federal Bank for Savings,Chicago,IL,30570,Royal Savings Bank,"December 15, 2017",10530
9,The Farmers and Merchants State Bank of Argonia,Argonia,KS,17719,Conway Bank,"October 13, 2017",10529
10,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
11,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
12,First NBC Bank,New Orleans,LA,58302,Whitney Bank,"April 28, 2017",10526
13,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,"March 3, 2017",10525
14,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,"January 27, 2017",10524
15,Harvest Community Bank,Pennsville,NJ,34951,First-Citizens Bank & Trust Company,"January 13, 2017",10523
16,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016",10522
17,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016",10521
18,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016",10520
19,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016",10519
20,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016",10518
21,Hometown National Bank,Longview,WA,35156,Twin City Bank,"October 2, 2015",10517
22,The Bank of Georgia,Peachtree City,GA,35259,Fidelity Bank,"October 2, 2015",10516
23,Premier Bank,Denver,CO,34112,"United Fidelity Bank, fsb","July 10, 2015",10515
24,Edgebrook Bank,Chicago,IL,57772,Republic Bank of Chicago,"May 8, 2015",10514
25,Doral Bank En Español,San Juan,PR,32102,Banco Popular de Puerto Rico,"February 27, 2015",10513
26,Capitol City Bank & Trust Company,Atlanta,GA,33938,First-Citizens Bank & Trust Company,"February 13, 2015",10512
27,Highland Community Bank,Chicago,IL,20290,"United Fidelity Bank, fsb","January 23, 2015",10511
28,First National Bank of Crestview,Crestview,FL,17557,First NBC Bank,"January 16, 2015",10510
29,Northern Star Bank,Mankato,MN,34983,BankVista,"December 19, 2014",10509
30,"Frontier Bank, FSB D/B/A El Paseo Bank",Palm Desert,CA,34738,"Bank of Southern California, N.A.","November 7, 2014",10508
31,The National Republic Bank of Chicago,Chicago,IL,916,State Bank of Texas,"October 24, 2014",10507
32,NBRS Financial,Rising Sun,MD,4862,Howard Bank,"October 17, 2014",10506
33,"GreenChoice Bank, fsb",Chicago,IL,28462,"Providence Bank, LLC","July 25, 2014",10505
34,Eastside Commercial Bank,Conyers,GA,58125,Community & Southern Bank,"July 18, 2014",10504
35,The Freedom State Bank,Freedom,OK,12483,Alva State Bank & Trust Company,"June 27, 2014",10503
36,Valley Bank,Fort Lauderdale,FL,21793,"Landmark Bank, National Association","June 20, 2014",10501
37,Valley Bank,Moline,IL,10450,Great Southern Bank,"June 20, 2014",10502
38,Slavie Federal Savings Bank,Bel Air,MD,32368,"Bay Bank, FSB","May 30, 2014",10500
39,Columbia Savings Bank,Cincinnati,OH,32284,"United Fidelity Bank, fsb","May 23, 2014",10499
40,AztecAmerica Bank En Español,Berwyn,IL,57866,Republic Bank of Chicago,"May 16, 2014",10498
41,Allendale County Bank,Fairfax,SC,15062,Palmetto State Bank,"April 25, 2014",10497
42,Vantage Point Bank,Horsham,PA,58531,First Choice Bank,"February 28, 2014",10496
43,"Millennium Bank, National Association",Sterling,VA,35096,WashingtonFirst Bank,"February 28, 2014",10495
44,Syringa Bank,Boise,ID,34296,Sunwest Bank,"January 31, 2014",10494
45,The Bank of Union,El Reno,OK,17967,BancFirst,"January 24, 2014",10493
46,DuPage National Bank,West Chicago,IL,5732,Republic Bank of Chicago,"January 17, 2014",10492
47,"Texas Community Bank, National Association",The Woodlands,TX,57431,"Spirit of Texas Bank, SSB","December 13, 2013",10491
48,Bank of Jackson County,Graceville,FL,14794,First Federal Bank of Florida,"October 30, 2013",10490
49,First National Bank also operating as The Nati...,Edinburg,TX,14318,PlainsCapital Bank,"September 13, 2013",10488
50,The Community's Bank,Bridgeport,CT,57041,No Acquirer,"September 13, 2013",10489
51,Sunrise Bank of Arizona,Phoenix,AZ,34707,"First Fidelity Bank, National Association","August 23, 2013",10487
52,Community South Bank,Parsons,TN,19849,"CB&S Bank, Inc.","August 23, 2013",10486
53,Bank of Wausau,Wausau,WI,35016,Nicolet National Bank,"August 9, 2013",10485
54,First Community Bank of Southwest Florida (als...,Fort Myers,FL,34943,C1 Bank,"August 2, 2013",10484
55,Mountain National Bank,Sevierville,TN,34789,"First Tennessee Bank, National Association","June 7, 2013",10483
56,1st Commerce Bank,North Las Vegas,NV,58358,Plaza Bank,"June 6, 2013",10482
57,Banks of Wisconsin d/b/a Bank of Kenosha,Kenosha,WI,35386,"North Shore Bank, FSB","May 31, 2013",10478
58,Central Arizona Bank,Scottsdale,AZ,34527,Western State Bank,"May 14, 2013",10479
59,Sunrise Bank,Valdosta,GA,58185,Synovus Bank,"May 10, 2013",10481
60,Pisgah Community Bank,Asheville,NC,58701,"Capital Bank, N.A.","May 10, 2013",10480
61,Douglas County Bank,Douglasville,GA,21649,Hamilton State Bank,"April 26, 2013",10476
62,Parkway Bank,Lenoir,NC,57158,"CertusBank, National Association","April 26, 2013",10477
63,Chipola Community Bank,Marianna,FL,58034,First Federal Bank of Florida,"April 19, 2013",10473
64,Heritage Bank of North Florida,Orange Park,FL,26680,FirstAtlantic Bank,"April 19, 2013",10475
65,First Federal Bank,Lexington,KY,29594,Your Community Bank,"April 19, 2013",10474
66,Gold Canyon Bank,Gold Canyon,AZ,58066,"First Scottsdale Bank, National Association","April 5, 2013",10472
67,Frontier Bank,LaGrange,GA,16431,HeritageBank of the South,"March 8, 2013",10471
68,Covenant Bank,Chicago,IL,22476,Liberty Bank and Trust Company,"February 15, 2013",10470
69,1st Regents Bank,Andover,MN,57157,First Minnesota Bank,"January 18, 2013",10469
70,Westside Community Bank,University Place,WA,33997,Sunwest Bank,"January 11, 2013",10468
71,Community Bank of the Ozarks,Sunrise Beach,MO,27331,Bank of Sullivan,"December 14, 2012",10467
72,Hometown Community Bank,Braselton,GA,57928,"CertusBank, National Association","November 16, 2012",10466
73,Citizens First National Bank,Princeton,IL,3731,Heartland Bank and Trust Company,"November 2, 2012",10464
74,Heritage Bank of Florida,Lutz,FL,35009,Centennial Bank,"November 2, 2012",10465
75,NOVA Bank,Berwyn,PA,27148,No Acquirer,"October 26, 2012",10463
76,Excel Bank,Sedalia,MO,19189,Simmons First National Bank,"October 19, 2012",10460
77,First East Side Savings Bank,Tamarac,FL,28144,Stearns Bank N.A.,"October 19, 2012",10461
78,GulfSouth Private Bank,Destin,FL,58073,SmartBank,"October 19, 2012",10462
79,First United Bank,Crete,IL,20685,"Old Plank Trail Community Bank, National Assoc...","September 28, 2012",10459
80,Truman Bank,St. Louis,MO,27316,Simmons First National Bank,"September 14, 2012",10458
81,First Commercial Bank,Bloomington,MN,35246,Republic Bank & Trust Company,"September 7, 2012",10457
82,Waukegan Savings Bank,Waukegan,IL,28243,First Midwest Bank,"August 3, 2012",10456
83,Jasper Banking Company,Jasper,GA,16240,Stearns Bank N.A.,"July 27, 2012",10455
84,Second Federal Savings and Loan Association of...,Chicago,IL,27986,Hinsdale Bank & Trust Company,"July 20, 2012",10453
85,Heartland Bank,Leawood,KS,1361,Metcalf Bank,"July 20, 2012",10452
86,First Cherokee State Bank,Woodstock,GA,32711,Community & Southern Bank,"July 20, 2012",10450
87,Georgia Trust Bank,Buford,GA,57847,Community & Southern Bank,"July 20, 2012",10451
88,The Royal Palm Bank of Florida,Naples,FL,57096,First National Bank of the Gulf Coast,"July 20, 2012",10454
89,Glasgow Savings Bank,Glasgow,MO,1056,Regional Missouri Bank,"July 13, 2012",10449
90,Montgomery Bank & Trust,Ailey,GA,19498,Ameris Bank,"July 6, 2012",10448
91,The Farmers Bank of Lynchburg,Lynchburg,TN,1690,Clayton Bank and Trust,"June 15, 2012",10447
92,Security Exchange Bank,Marietta,GA,35299,Fidelity Bank,"June 15, 2012",10446
93,Putnam State Bank,Palatka,FL,27405,Harbor Community Bank,"June 15, 2012",10445
94,Waccamaw Bank,Whiteville,NC,34515,First Community Bank,"June 8, 2012",10444
95,Farmers' and Traders' State Bank,Shabbona,IL,9257,First State Bank,"June 8, 2012",10442
96,Carolina Federal Savings Bank,Charleston,SC,35372,Bank of North Carolina,"June 8, 2012",10441
97,First Capital Bank,Kingfisher,OK,416,F & M Bank,"June 8, 2012",10443
98,"Alabama Trust Bank, National Association",Sylacauga,AL,35224,Southern States Bank,"May 18, 2012",10440
99,"Security Bank, National Association",North Lauderdale,FL,23156,Banesco USA,"May 4, 2012",10439
100,Palm Desert National Bank,Palm Desert,CA,23632,Pacific Premier Bank,"April 27, 2012",10437
101,Plantation Federal Bank,Pawleys Island,SC,32503,First Federal Bank,"April 27, 2012",10438
102,"Inter Savings Bank, fsb D/B/A InterBank, fsb",Maple Grove,MN,31495,Great Southern Bank,"April 27, 2012",10436
103,HarVest Bank of Maryland,Gaithersburg,MD,57766,Sonabank,"April 27, 2012",10435
104,Bank of the Eastern Shore,Cambridge,MD,26759,No Acquirer,"April 27, 2012",10434
105,"Fort Lee Federal Savings Bank, FSB",Fort Lee,NJ,35527,Alma Bank,"April 20, 2012",10433
106,Fidelity Bank,Dearborn,MI,33883,The Huntington National Bank,"March 30, 2012",10432
107,Premier Bank,Wilmette,IL,35419,International Bank of Chicago,"March 23, 2012",10431
108,Covenant Bank & Trust,Rock Spring,GA,58068,"Stearns Bank, N.A.","March 23, 2012",10430
109,New City Bank,Chicago,IL,57597,No Acquirer,"March 9, 2012",10429
110,Global Commerce Bank,Doraville,GA,34046,Metro City Bank,"March 2, 2012",10428
111,Home Savings of America,Little Falls,MN,29178,No Acquirer,"February 24, 2012",10427
112,Central Bank of Georgia,Ellaville,GA,5687,Ameris Bank,"February 24, 2012",10426
113,SCB Bank,Shelbyville,IN,29761,"First Merchants Bank, National Association","February 10, 2012",10425
114,Charter National Bank and Trust,Hoffman Estates,IL,23187,"Barrington Bank & Trust Company, National Asso...","February 10, 2012",10424
115,BankEast,Knoxville,TN,19869,"U.S. Bank, N.A.","January 27, 2012",10420
116,Patriot Bank Minnesota,Forest Lake,MN,34823,First Resource Bank,"January 27, 2012",10422
117,Tennessee Commerce Bank,Franklin,TN,35296,Republic Bank & Trust Company,"January 27, 2012",10423
118,First Guaranty Bank and Trust Company of Jacks...,Jacksonville,FL,16579,"CenterState Bank of Florida, N.A.","January 27, 2012",10421
119,American Eagle Savings Bank,Boothwyn,PA,31581,"Capital Bank, N.A.","January 20, 2012",10417
120,The First State Bank,Stockbridge,GA,19252,Hamilton State Bank,"January 20, 2012",10419
121,Central Florida State Bank,Belleview,FL,57186,"CenterState Bank of Florida, N.A.","January 20, 2012",10418
122,Western National Bank,Phoenix,AZ,57917,Washington Federal,"December 16, 2011",10416
123,Premier Community Bank of the Emerald Coast,Crestview,FL,58343,Summit Bank,"December 16, 2011",10415
124,Central Progressive Bank,Lacombe,LA,19657,First NBC Bank,"November 18, 2011",10413
125,Polk County Bank,Johnston,IA,14194,Grinnell State Bank,"November 18, 2011",10414
126,Community Bank of Rockmart,Rockmart,GA,57860,Century Bank of Georgia,"November 10, 2011",10412
127,SunFirst Bank,Saint George,UT,57087,Cache Valley Bank,"November 4, 2011",10411
128,"Mid City Bank, Inc.",Omaha,NE,19397,Premier Bank,"November 4, 2011",10410
129,All American Bank,Des Plaines,IL,57759,International Bank of Chicago,"October 28, 2011",10409
130,Community Banks of Colorado,Greenwood Village,CO,21132,"Bank Midwest, N.A.","October 21, 2011",10405
131,Community Capital Bank,Jonesboro,GA,57036,State Bank and Trust Company,"October 21, 2011",10406
132,Decatur First Bank,Decatur,GA,34392,Fidelity Bank,"October 21, 2011",10407
133,Old Harbor Bank,Clearwater,FL,57537,1st United Bank,"October 21, 2011",10408
134,Country Bank,Aledo,IL,35395,Blackhawk Bank & Trust,"October 14, 2011",10402
135,First State Bank,Cranford,NJ,58046,Northfield Bank,"October 14, 2011",10403
136,"Blue Ridge Savings Bank, Inc.",Asheville,NC,32347,Bank of North Carolina,"October 14, 2011",10401
137,Piedmont Community Bank,Gray,GA,57256,State Bank and Trust Company,"October 14, 2011",10404
138,Sun Security Bank,Ellington,MO,20115,Great Southern Bank,"October 7, 2011",10400
139,The RiverBank,Wyoming,MN,10216,Central Bank,"October 7, 2011",10399
140,First International Bank,Plano,TX,33513,American First National Bank,"September 30, 2011",10398
141,Citizens Bank of Northern California,Nevada City,CA,33983,Tri Counties Bank,"September 23, 2011",10397
142,Bank of the Commonwealth,Norfolk,VA,20408,Southern Bank and Trust Company,"September 23, 2011",10396
143,The First National Bank of Florida,Milton,FL,25155,CharterBank,"September 9, 2011",10395
144,CreekSide Bank,Woodstock,GA,58226,Georgia Commerce Bank,"September 2, 2011",10393
145,Patriot Bank of Georgia,Cumming,GA,58273,Georgia Commerce Bank,"September 2, 2011",10394
146,First Choice Bank,Geneva,IL,57212,Inland Bank & Trust,"August 19, 2011",10390
147,First Southern National Bank,Statesboro,GA,57239,Heritage Bank of the South,"August 19, 2011",10391
148,Lydian Private Bank,Palm Beach,FL,35356,"Sabadell United Bank, N.A.","August 19, 2011",10392
149,Public Savings Bank,Huntingdon Valley,PA,34130,"Capital Bank, N.A.","August 18, 2011",10389
150,The First National Bank of Olathe,Olathe,KS,4744,Enterprise Bank & Trust,"August 12, 2011",10388
151,Bank of Whitman,Colfax,WA,22528,Columbia State Bank,"August 5, 2011",10387
152,Bank of Shorewood,Shorewood,IL,22637,Heartland Bank and Trust Company,"August 5, 2011",10386
153,Integra Bank National Association,Evansville,IN,4392,Old National Bank,"July 29, 2011",10384
154,"BankMeridian, N.A.",Columbia,SC,58222,SCBT National Association,"July 29, 2011",10383
155,Virginia Business Bank,Richmond,VA,58283,Xenith Bank,"July 29, 2011",10385
156,Bank of Choice,Greeley,CO,2994,"Bank Midwest, N.A.","July 22, 2011",10380
157,LandMark Bank of Florida,Sarasota,FL,35244,American Momentum Bank,"July 22, 2011",10381
158,Southshore Community Bank,Apollo Beach,FL,58056,American Momentum Bank,"July 22, 2011",10382
159,Summit Bank,Prescott,AZ,57442,The Foothills Bank,"July 15, 2011",10379
160,First Peoples Bank,Port St. Lucie,FL,34870,"Premier American Bank, N.A.","July 15, 2011",10376
161,High Trust Bank,Stockbridge,GA,19554,Ameris Bank,"July 15, 2011",10377
162,One Georgia Bank,Atlanta,GA,58238,Ameris Bank,"July 15, 2011",10378
163,Signature Bank,Windsor,CO,57835,Points West Community Bank,"July 8, 2011",10375
164,Colorado Capital Bank,Castle Rock,CO,34522,First-Citizens Bank & Trust Company,"July 8, 2011",10373
165,First Chicago Bank & Trust,Chicago,IL,27935,Northbrook Bank & Trust Company,"July 8, 2011",10374
166,Mountain Heritage Bank,Clayton,GA,57593,First American Bank and Trust Company,"June 24, 2011",10372
167,First Commercial Bank of Tampa Bay,Tampa,FL,27583,Stonegate Bank,"June 17, 2011",10370
168,McIntosh State Bank,Jackson,GA,19237,Hamilton State Bank,"June 17, 2011",10371
169,Atlantic Bank and Trust,Charleston,SC,58420,"First Citizens Bank and Trust Company, Inc.","June 3, 2011",10369
170,First Heritage Bank,Snohomish,WA,23626,Columbia State Bank,"May 27, 2011",10368
171,Summit Bank,Burlington,WA,513,Columbia State Bank,"May 20, 2011",10367
172,First Georgia Banking Company,Franklin,GA,57647,"CertusBank, National Association","May 20, 2011",10366
173,Atlantic Southern Bank,Macon,GA,57213,"CertusBank, National Association","May 20, 2011",10365
174,Coastal Bank,Cocoa Beach,FL,34898,"Florida Community Bank, a division of Premier ...","May 6, 2011",10364
175,Community Central Bank,Mount Clemens,MI,34234,Talmer Bank & Trust,"April 29, 2011",10359
176,The Park Avenue Bank,Valdosta,GA,19797,Bank of the Ozarks,"April 29, 2011",10363
177,First Choice Community Bank,Dallas,GA,58539,Bank of the Ozarks,"April 29, 2011",10361
178,Cortez Community Bank,Brooksville,FL,57625,"Florida Community Bank, a division of Premier ...","April 29, 2011",10360
179,First National Bank of Central Florida,Winter Park,FL,26297,"Florida Community Bank, a division of Premier ...","April 29, 2011",10362
180,Heritage Banking Group,Carthage,MS,14273,Trustmark National Bank,"April 15, 2011",10354
181,Rosemount National Bank,Rosemount,MN,24099,Central Bank,"April 15, 2011",10357
182,Superior Bank,Birmingham,AL,17750,"Superior Bank, National Association","April 15, 2011",10358
183,Nexity Bank,Birmingham,AL,19794,AloStar Bank of Commerce,"April 15, 2011",10356
184,New Horizons Bank,East Ellijay,GA,57705,Citizens South Bank,"April 15, 2011",10355
185,Bartow County Bank,Cartersville,GA,21495,Hamilton State Bank,"April 15, 2011",10353
186,Nevada Commerce Bank,Las Vegas,NV,35418,City National Bank,"April 8, 2011",10351
187,Western Springs National Bank and Trust,Western Springs,IL,10086,Heartland Bank and Trust Company,"April 8, 2011",10352
188,The Bank of Commerce,Wood Dale,IL,34292,Advantage National Bank Group,"March 25, 2011",10350
189,Legacy Bank,Milwaukee,WI,34818,Seaway Bank and Trust Company,"March 11, 2011",10348
190,First National Bank of Davis,Davis,OK,4077,The Pauls Valley National Bank,"March 11, 2011",10349
191,Valley Community Bank,St. Charles,IL,34187,First State Bank,"February 25, 2011",10347
192,"San Luis Trust Bank, FSB",San Luis Obispo,CA,34783,First California Bank,"February 18, 2011",10346
193,Charter Oak Bank,Napa,CA,57855,Bank of Marin,"February 18, 2011",10343
194,Citizens Bank of Effingham,Springfield,GA,34601,Heritage Bank of the South,"February 18, 2011",10344
195,Habersham Bank,Clarkesville,GA,151,SCBT National Association,"February 18, 2011",10345
196,Canyon National Bank,Palm Springs,CA,34692,Pacific Premier Bank,"February 11, 2011",10340
197,Badger State Bank,Cassville,WI,13272,Royal Bank,"February 11, 2011",10339
198,Peoples State Bank,Hamtramck,MI,14939,First Michigan Bank,"February 11, 2011",10341
199,Sunshine State Community Bank,Port Orange,FL,35478,"Premier American Bank, N.A.","February 11, 2011",10342
200,Community First Bank Chicago,Chicago,IL,57948,Northbrook Bank & Trust Company,"February 4, 2011",10337
201,North Georgia Bank,Watkinsville,GA,35242,BankSouth,"February 4, 2011",10338
202,American Trust Bank,Roswell,GA,57432,Renasant Bank,"February 4, 2011",10336
203,First Community Bank,Taos,NM,12261,"U.S. Bank, N.A.","January 28, 2011",10333
204,FirsTier Bank,Louisville,CO,57646,No Acquirer,"January 28, 2011",10334
205,Evergreen State Bank,Stoughton,WI,5328,McFarland State Bank,"January 28, 2011",10332
206,The First State Bank,Camargo,OK,2303,Bank 7,"January 28, 2011",10335
207,United Western Bank,Denver,CO,31293,First-Citizens Bank & Trust Company,"January 21, 2011",10331
208,The Bank of Asheville,Asheville,NC,34516,First Bank,"January 21, 2011",10330
209,CommunitySouth Bank & Trust,Easley,SC,57868,"CertusBank, National Association","January 21, 2011",10328
210,Enterprise Banking Company,McDonough,GA,19758,No Acquirer,"January 21, 2011",10329
211,Oglethorpe Bank,Brunswick,GA,57440,Bank of the Ozarks,"January 14, 2011",10327
212,Legacy Bank,Scottsdale,AZ,57820,Enterprise Bank & Trust,"January 7, 2011",10326
213,First Commercial Bank of Florida,Orlando,FL,34965,First Southern Bank,"January 7, 2011",10325
214,Community National Bank,Lino Lakes,MN,23306,Farmers & Merchants Savings Bank,"December 17, 2010",10321

# CSV 
## csv input

In [17]:
df

[                                         Bank NameBank            CityCity  \
 0                                    Almena State Bank              Almena
 1                           First City Bank of Florida   Fort Walton Beach
 2                                 The First State Bank       Barboursville
 3                                   Ericson State Bank             Ericson
 4                     City National Bank of New Jersey              Newark
 5                                        Resolute Bank              Maumee
 6                                Louisa Community Bank              Louisa
 7                                 The Enloe State Bank              Cooper
 8                  Washington Federal Bank for Savings             Chicago
 9      The Farmers and Merchants State Bank of Argonia             Argonia
 10                                 Fayette County Bank          Saint Elmo
 11   Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 12                                      First NBC Bank         New Orleans
 13                                       Proficio Bank  Cottonwood Heights
 14                       Seaway Bank and Trust Company             Chicago
 15                              Harvest Community Bank          Pennsville
 16                                         Allied Bank            Mulberry
 17                        The Woodbury Banking Company            Woodbury
 18                              First CornerStone Bank     King of Prussia
 19                                  Trust Company Bank             Memphis
 20                          North Milwaukee State Bank           Milwaukee
 21                              Hometown National Bank            Longview
 22                                 The Bank of Georgia      Peachtree City
 23                                        Premier Bank              Denver
 24                                      Edgebrook Bank             Chicago
 25                              Doral Bank  En Español            San Juan
 26                   Capitol City Bank & Trust Company             Atlanta
 27                             Highland Community Bank             Chicago
 28                    First National Bank of Crestview           Crestview
 29                                  Northern Star Bank             Mankato
 30              Frontier Bank, FSB D/B/A El Paseo Bank         Palm Desert
 31               The National Republic Bank of Chicago             Chicago
 32                                      NBRS Financial          Rising Sun
 33                               GreenChoice Bank, fsb             Chicago
 34                            Eastside Commercial Bank             Conyers
 35                              The Freedom State Bank             Freedom
 36                                         Valley Bank     Fort Lauderdale
 37                                         Valley Bank              Moline
 38                         Slavie Federal Savings Bank             Bel Air
 39                               Columbia Savings Bank          Cincinnati
 40                       AztecAmerica Bank  En Español              Berwyn
 41                               Allendale County Bank             Fairfax
 42                                  Vantage Point Bank             Horsham
 43               Millennium Bank, National Association            Sterling
 44                                        Syringa Bank               Boise
 45                                   The Bank of Union             El Reno
 46                                DuPage National Bank        West Chicago
 47          Texas Community Bank, National Association       The Woodlands
 48                              Bank of Jackson County          Graceville
 49   First National Bank also operating as The Nati...            Edinburg
 50                                The Community's Bank          Bridgeport
 51                             Sunrise Bank of Arizona             Phoenix
 52                                Community South Bank             Parsons
 53                                      Bank of Wausau              Wausau
 54   First Community Bank of Southwest Florida (als...          Fort Myers
 55                              Mountain National Bank         Sevierville
 56                                   1st Commerce Bank     North Las Vegas
 57            Banks of Wisconsin d/b/a Bank of Kenosha             Kenosha
 58                                Central Arizona Bank          Scottsdale
 59                                        Sunrise Bank            Valdosta
 60                               Pisgah Community Bank           Asheville
 61                                 Douglas County Bank        Douglasville
 62                                        Parkway Bank              Lenoir
 63                              Chipola Community Bank            Marianna
 64                      Heritage Bank of North Florida         Orange Park
 65                                  First Federal Bank           Lexington
 66                                    Gold Canyon Bank         Gold Canyon
 67                                       Frontier Bank            LaGrange
 68                                       Covenant Bank             Chicago
 69                                    1st Regents Bank             Andover
 70                             Westside Community Bank    University Place
 71                        Community Bank of the Ozarks       Sunrise Beach
 72                             Hometown Community Bank           Braselton
 73                        Citizens First National Bank           Princeton
 74                            Heritage Bank of Florida                Lutz
 75                                           NOVA Bank              Berwyn
 76                                          Excel Bank             Sedalia
 77                        First East Side Savings Bank             Tamarac
 78                              GulfSouth Private Bank              Destin
 79                                   First United Bank               Crete
 80                                         Truman Bank           St. Louis
 81                               First Commercial Bank         Bloomington
 82                               Waukegan Savings Bank            Waukegan
 83                              Jasper Banking Company              Jasper
 84   Second Federal Savings and Loan Association of...             Chicago
 85                                      Heartland Bank             Leawood
 86                           First Cherokee State Bank           Woodstock
 87                                  Georgia Trust Bank              Buford
 88                      The Royal Palm Bank of Florida              Naples
 89                                Glasgow Savings Bank             Glasgow
 90                             Montgomery Bank & Trust               Ailey
 91                       The Farmers Bank of Lynchburg           Lynchburg
 92                              Security Exchange Bank            Marietta
 93                                   Putnam State Bank             Palatka
 94                                       Waccamaw Bank          Whiteville
 95                    Farmers' and Traders' State Bank            Shabbona
 96                       Carolina Federal Savings Bank          Charleston
 97                                  First Capital Bank          Kingfisher
 98            Alabama Trust Bank, National Association           Sylacauga
 99                 Security Bank, National Association    North Lauderdale
 100                          Palm Desert National Bank         Palm Desert
 101                            Plantation Federal Bank      Pawleys Island
 102       Inter Savings Bank, fsb D/B/A InterBank, fsb         Maple Grove
 103                           HarVest Bank of Maryland        Gaithersburg
 104                          Bank of the Eastern Shore           Cambridge
 105                 Fort Lee Federal Savings Bank, FSB            Fort Lee
 106                                      Fidelity Bank            Dearborn
 107                                       Premier Bank            Wilmette
 108                              Covenant Bank & Trust         Rock Spring
 109                                      New City Bank             Chicago
 110                               Global Commerce Bank           Doraville
 111                            Home Savings of America        Little Falls
 112                            Central Bank of Georgia           Ellaville
 113                                           SCB Bank         Shelbyville
 114                    Charter National Bank and Trust     Hoffman Estates
 115                                           BankEast           Knoxville
 116                             Patriot Bank Minnesota         Forest Lake
 117                            Tennessee Commerce Bank            Franklin
 118  First Guaranty Bank and Trust Company of Jacks...        Jacksonville
 119                        American Eagle Savings Bank            Boothwyn
 120                               The First State Bank         Stockbridge
 121                         Central Florida State Bank           Belleview
 122                              Western National Bank             Phoenix
 123        Premier Community Bank of the Emerald Coast           Crestview
 124                           Central Progressive Bank             Lacombe
 125                                   Polk County Bank            Johnston
 126                         Community Bank of Rockmart            Rockmart
 127                                      SunFirst Bank        Saint George
 128                                Mid City Bank, Inc.               Omaha
 129                                  All American Bank         Des Plaines
 130                        Community Banks of Colorado   Greenwood Village
 131                             Community Capital Bank           Jonesboro
 132                                 Decatur First Bank             Decatur
 133                                    Old Harbor Bank          Clearwater
 134                                       Country Bank               Aledo
 135                                   First State Bank            Cranford
 136                      Blue Ridge Savings Bank, Inc.           Asheville
 137                            Piedmont Community Bank                Gray
 138                                  Sun Security Bank           Ellington
 139                                      The RiverBank             Wyoming
 140                           First International Bank               Plano
 141               Citizens Bank of Northern California         Nevada City
 142                           Bank of the Commonwealth             Norfolk
 143                 The First National Bank of Florida              Milton
 144                                     CreekSide Bank           Woodstock
 145                            Patriot Bank of Georgia             Cumming
 146                                  First Choice Bank              Geneva
 147                       First Southern National Bank          Statesboro
 148                                Lydian Private Bank          Palm Beach
 149                                Public Savings Bank   Huntingdon Valley
 150                  The First National Bank of Olathe              Olathe
 151                                    Bank of Whitman              Colfax
 152                                  Bank of Shorewood           Shorewood
 153                  Integra Bank National Association          Evansville
 154                                 BankMeridian, N.A.            Columbia
 155                             Virginia Business Bank            Richmond
 156                                     Bank of Choice             Greeley
 157                           LandMark Bank of Florida            Sarasota
 158                          Southshore Community Bank        Apollo Beach
 159                                        Summit Bank            Prescott
 160                                 First Peoples Bank      Port St. Lucie
 161                                    High Trust Bank         Stockbridge
 162                                   One Georgia Bank             Atlanta
 163                                     Signature Bank             Windsor
 164                              Colorado Capital Bank         Castle Rock
 165                         First Chicago Bank & Trust             Chicago
 166                             Mountain Heritage Bank             Clayton
 167                 First Commercial Bank of Tampa Bay               Tampa
 168                                McIntosh State Bank             Jackson
 169                            Atlantic Bank and Trust          Charleston
 170                                First Heritage Bank           Snohomish
 171                                        Summit Bank          Burlington
 172                      First Georgia Banking Company            Franklin
 173                             Atlantic Southern Bank               Macon
 174                                       Coastal Bank         Cocoa Beach
 175                             Community Central Bank       Mount Clemens
 176                               The Park Avenue Bank            Valdosta
 177                        First Choice Community Bank              Dallas
 178                              Cortez Community Bank         Brooksville
 179             First National Bank of Central Florida         Winter Park
 180                             Heritage Banking Group            Carthage
 181                            Rosemount National Bank           Rosemount
 182                                      Superior Bank          Birmingham
 183                                        Nexity Bank          Birmingham
 184                                  New Horizons Bank        East Ellijay
 185                                 Bartow County Bank        Cartersville
 186                               Nevada Commerce Bank           Las Vegas
 187            Western Springs National Bank and Trust     Western Springs
 188                               The Bank of Commerce           Wood Dale
 189                                        Legacy Bank           Milwaukee
 190                       First National Bank of Davis               Davis
 191                              Valley Community Bank         St. Charles
 192                           San Luis Trust Bank, FSB     San Luis Obispo
 193                                   Charter Oak Bank                Napa
 194                         Citizens Bank of Effingham         Springfield
 195                                     Habersham Bank        Clarkesville
 196                               Canyon National Bank        Palm Springs
 197                                  Badger State Bank           Cassville
 198                                 Peoples State Bank           Hamtramck
 199                      Sunshine State Community Bank         Port Orange
 200                       Community First Bank Chicago             Chicago
 201                                 North Georgia Bank        Watkinsville
 202                                American Trust Bank             Roswell
 203                               First Community Bank                Taos
 204                                      FirsTier Bank          Louisville
 205                               Evergreen State Bank           Stoughton
 206                               The First State Bank             Camargo
 207                                United Western Bank              Denver
 208                              The Bank of Asheville           Asheville
 209                        CommunitySouth Bank & Trust              Easley
 210                         Enterprise Banking Company           McDonough
 211                                    Oglethorpe Bank           Brunswick
 212                                        Legacy Bank          Scottsdale
 213                   First Commercial Bank of Florida             Orlando
 214                            Community National Bank          Lino Lakes
 215                                First Southern Bank          Batesville
 216                         United Americas Bank, N.A.             Atlanta
 217                    Appalachian Community Bank, FSB         McCaysville
 218                               Chestatee State Bank         Dawsonville
 219                             The Bank of Miami,N.A.        Coral Gables
 220                                     Earthstar Bank         Southampton
 221                                     Paramount Bank    Farmington Hills
 222                               First Banking Center          Burlington
 223                   Allegiance Bank of North America         Bala Cynwyd
 224                          Gulf State Community Bank          Carrabelle
 225                                   Copper Star Bank          Scottsdale
 226                             Darby Bank & Trust Co.             Vidalia
 227                             Tifton Banking Company              Tifton
 228                     First Vietnamese American Bank         Westminster
 229                             Pierce Commercial Bank              Tacoma
 230                            Western Commercial Bank      Woodland Hills
 231                                             K Bank        Randallstown
 232                       First Arizona Savings, A FSB          Scottsdale
 233                                     Hillcrest Bank       Overland Park
 234                       First Suburban National Bank             Maywood
 235             The First National Bank of Barnesville         Barnesville
 236                                    The Gordon Bank              Gordon
 237                           Progress Bank of Florida               Tampa
 238                         First Bank of Jacksonville        Jacksonville
 239                                       Premier Bank      Jefferson City
 240                  WestBridge Bank and Trust Company        Chesterfield
 241                      Security Savings Bank, F.S.B.              Olathe
 242                                     Shoreline Bank           Shoreline
 243                                       Wakulla Bank       Crawfordville
 244                                  North County Bank           Arlington
 245                           Haven Trust Bank Florida   Ponte Vedra Beach
 246                              Maritime Savings Bank          West Allis
 247                               Bramble Savings Bank             Milford
 248                                   The Peoples Bank              Winder
 249                      First Commerce Community Bank        Douglasville
 250                                    Bank of Ellijay             Ellijay
 251                                           ISN Bank         Cherry Hill
 252                                       Horizon Bank           Bradenton
 253                                 Sonoma Valley Bank              Sonoma
 254                                    Los Padres Bank             Solvang
 255                               Butte Community Bank               Chico
 256                                 Pacific State Bank            Stockton
 257                                          ShoreBank             Chicago
 258              Imperial Savings and Loan Association        Martinsville
 259                          Independent National Bank               Ocala
 260                  Community National Bank at Bartow              Bartow
 261                       Palos Bank and Trust Company       Palos Heights

In [18]:
df.head()

AttributeError: 'list' object has no attribute 'head'

In [ ]:
# saving as a csv file using to_csv method
df.to_csv('example',index=False)

In [ ]:
df = pd.read_csv('example')
df

In [ ]:
# to get the names of the columns
df.columns

In [ ]:
# to obtain more information about your data frame columns
df.info()

In [ ]:
new_columns = ['NameBank', 'City', 'State', 'Cert', 'Acquiring_InstitutionAI', 'Date_Closing', 'Fund']

In [ ]:
df.columns = new_columns

In [ ]:
df.head(2)

# Excel
* ### pandas can read and write excel files, keep in mind this only imports data

## Excel input

In [20]:
pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [25]:
Excel.head()

NameError: name 'Excel' is not defined

# Groupby Method

In [29]:
group_df = df.groupby(['State','Fund'])

AttributeError: 'list' object has no attribute 'groupby'

In [30]:
group_df.mean()

NameError: name 'group_df' is not defined

# HTML

In [32]:
!pip install html5lib

Requirement already satisfied: html5lib in /Users/myamwalker/opt/anaconda3/lib/python3.9/site-packages (1.1)
Requirement already satisfied: six>=1.9 in /Users/myamwalker/opt/anaconda3/lib/python3.9/site-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in /Users/myamwalker/opt/anaconda3/lib/python3.9/site-packages (from html5lib) (0.5.1)

In [33]:
! pip install lxml

Requirement already satisfied: lxml in /Users/myamwalker/opt/anaconda3/lib/python3.9/site-packages (4.8.0)

In [34]:
! pip install BeautifulSoup4

Requirement already satisfied: BeautifulSoup4 in /Users/myamwalker/opt/anaconda3/lib/python3.9/site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in /Users/myamwalker/opt/anaconda3/lib/python3.9/site-packages (from BeautifulSoup4) (2.3.1)

In [36]:
pd.set_option('display.max_rows',563)
pd.set_option('display.max_columns',7)

In [37]:
df = df[0]

In [38]:
df.columns

Index(['Bank NameBank', 'CityCity', 'StateSt', 'CertCert',
       'Acquiring InstitutionAI', 'Closing DateClosing', 'FundFund'],
      dtype='object')

In [39]:
new_names = ['Bank_Name', 'City', 'State', 'Cert', 'InstitutionAI', 'Closing_Date', 'Fund']

In [40]:
df.columns = new_names

In [41]:
df.head(2)

,Bank_Name,City,State,Cert,InstitutionAI,Closing_Date,Fund
0,Almena State Bank,Almena,KS,15426,Equity Bank,"October 23, 2020",10538
1,First City Bank of Florida,Fort Walton Beach,FL,16748,"United Fidelity Bank, fsb","October 16, 2020",10537

In [42]:
df['Closing_Date'].dtypes

dtype('O')

In [43]:
df['date'] = pd.to_datetime(df['Closing_Date'])

In [44]:
df.head()

,Bank_Name,City,State,...,Closing_Date,Fund,date
0,Almena State Bank,Almena,KS,...,"October 23, 2020",10538,2020-10-23
1,First City Bank of Florida,Fort Walton Beach,FL,...,"October 16, 2020",10537,2020-10-16
2,The First State Bank,Barboursville,WV,...,"April 3, 2020",10536,2020-04-03
3,Ericson State Bank,Ericson,NE,...,"February 14, 2020",10535,2020-02-14
4,City National Bank of New Jersey,Newark,NJ,...,"November 1, 2019",10534,2019-11-01

In [45]:
# dropping the Closing_Date coumn
df.drop('Closing_Date',axis=1,inplace=True)

In [47]:
df.head()

,Bank_Name,City,State,Cert,InstitutionAI,Fund,date
0,Almena State Bank,Almena,KS,15426,Equity Bank,10538,2020-10-23
1,First City Bank of Florida,Fort Walton Beach,FL,16748,"United Fidelity Bank, fsb",10537,2020-10-16
2,The First State Bank,Barboursville,WV,14361,"MVB Bank, Inc.",10536,2020-04-03
3,Ericson State Bank,Ericson,NE,18265,Farmers and Merchants Bank,10535,2020-02-14
4,City National Bank of New Jersey,Newark,NJ,21111,Industrial Bank,10534,2019-11-01

In [48]:
df['date'].dtypes

dtype('<M8[ns]')

In [49]:
#df['date'] =df['date'].apply(lambda x: x.split('-'))

In [50]:
#convert the datetime object to a string
df['date'] = df['date'].astype('string')

In [51]:
df['date'].dtypes

string[python]

In [53]:
df['Year'] =df['date'].apply(lambda x: x.split('-')[0])
df['Month'] =df['date'].apply(lambda x: x.split('-')[1])
df['Day'] =df['date'].apply(lambda x: x.split('-')[2])

In [65]:
pd.set_option('display.max_columns',None)

In [66]:
df.head()

,Bank_Name,City,State,Cert,InstitutionAI,Fund,date,Year,Month,Day
0,Almena State Bank,Almena,KS,15426,Equity Bank,10538,2020-10-23,2020,10,23
1,First City Bank of Florida,Fort Walton Beach,FL,16748,"United Fidelity Bank, fsb",10537,2020-10-16,2020,10,16
2,The First State Bank,Barboursville,WV,14361,"MVB Bank, Inc.",10536,2020-04-03,2020,04,03
3,Ericson State Bank,Ericson,NE,18265,Farmers and Merchants Bank,10535,2020-02-14,2020,02,14
4,City National Bank of New Jersey,Newark,NJ,21111,Industrial Bank,10534,2019-11-01,2019,11,01

In [68]:
df.drop('date',axis=1,inplace=True)

In [69]:
df.head()

,Bank_Name,City,State,Cert,InstitutionAI,Fund,Year,Month,Day
0,Almena State Bank,Almena,KS,15426,Equity Bank,10538,2020,10,23
1,First City Bank of Florida,Fort Walton Beach,FL,16748,"United Fidelity Bank, fsb",10537,2020,10,16
2,The First State Bank,Barboursville,WV,14361,"MVB Bank, Inc.",10536,2020,04,03
3,Ericson State Bank,Ericson,NE,18265,Farmers and Merchants Bank,10535,2020,02,14
4,City National Bank of New Jersey,Newark,NJ,21111,Industrial Bank,10534,2019,11,01

In [70]:
for idx, row in df.iterrows():
    print(row['State'])

KS
FL
WV
NE
NJ
OH
KY
TX
IL
KS
IL
WI
LA
UT
IL
NJ
AR
GA
PA
TN
WI
WA
GA
CO
IL
PR
GA
IL
FL
MN
CA
IL
MD
IL
GA
OK
FL
IL
MD
OH
IL
SC
PA
VA
ID
OK
IL
TX
FL
TX
CT
AZ
TN
WI
FL
TN
NV
WI
AZ
GA
NC
GA
NC
FL
FL
KY
AZ
GA
IL
MN
WA
MO
GA
IL
FL
PA
MO
FL
FL
IL
MO
MN
IL
GA
IL
KS
GA
GA
FL
MO
GA
TN
GA
FL
NC
IL
SC
OK
AL
FL
CA
SC
MN
MD
MD
NJ
MI
IL
GA
IL
GA
MN
GA
IN
IL
TN
MN
TN
FL
PA
GA
FL
AZ
FL
LA
IA
GA
UT
NE
IL
CO
GA
GA
FL
IL
NJ
NC
GA
MO
MN
TX
CA
VA
FL
GA
GA
IL
GA
FL
PA
KS
WA
IL
IN
SC
VA
CO
FL
FL
AZ
FL
GA
GA
CO
CO
IL
GA
FL
GA
SC
WA
WA
GA
GA
FL
MI
GA
GA
FL
FL
MS
MN
AL
AL
GA
GA
NV
IL
IL
WI
OK
IL
CA
CA
GA
GA
CA
WI
MI
FL
IL
GA
GA
NM
CO
WI
OK
CO
NC
SC
GA
GA
AZ
FL
MN
AR
GA
GA
GA
FL
PA
MI
WI
PA
FL
AZ
GA
GA
CA
WA
CA
MD
AZ
KS
IL
GA
GA
FL
FL
MO
MO
KS
WA
FL
WA
FL
WI
OH
GA
GA
GA
NJ
FL
CA
CA
CA
CA
IL
VA
FL
FL
IL
IL
OR
WA
FL
FL
GA
OR
NV
MN
KS
SC
GA
FL
MI
FL
FL
FL
SC
SC
OK
NY
MD
MD
NM
GA
FL
NV
WA
NE
IL
MS
NV
CA
FL
FL
FL
MN
IL
MO
MI
GA
CA
AZ
MN
FL
WA
MO
MO
MI
PR
PR
PR
IL
IL
IL
IL
IL
IL
IL
WA
CA
CA
MA
FL
FL
FL
MI
SC
AZ
GA
FL
GA
MN
AL
GA
GA
UT
GA
OH
LA
FL
NY
NY
UT
MD
IL
FL
WA
NV
CA
IL
TX
FL
MN
WA
CA
GA
MN
FL
GA
OR
WA
NM
MO
FL
UT
MN
IL
WA
CA
CA
IL
AL
MI
FL
GA
KS
AZ
FL
VA
IL
OH
GA
GA
GA
FL
CA
FL
FL
CA
MO
MN
MI
GA
TX
TX
TX
IL
CA
CA
CA
IL
AZ
IL
MN
WI
FL
FL
GA
FL
CA
CO
MN
MI
GA
KY
IN
WA
MN
IL
AZ
IL
IA
IL
MO
CA
MN
MD
TX
AL
GA
GA
NV
AZ
AZ
AL
PA
OR
FL
FL
IL
NJ
OH
FL
OK
GA
GA
GA
GA
GA
GA
NY
CA
CA
SD
GA
WY
IL
TX
IL
IL
IL
IL
IL
CA
CA
MN
GA
GA
KS
NC
GA
IL
IL
IL
FL
WA
UT
NJ
GA
ID
CA
MI
GA
NV
MO
CO
NC
GA
KS
CO
GA
GA
NV
IL
OR
OR
IL
FL
NE
CA
CA
GA
FL
MD
UT
CA
WA
IL
TX
GA
GA
CA
CA
GA
CA
TX
FL
GA
IL
MI
NV
WV
NV
GA
KS
FL
CA
NV
CA
MN
AR
MO
MO
OH
GA
PA
UT
NY
FL
NJ
PA
WI
CA
LA
TN
GA
IL
CT
MI
FL
AZ
OH
TX
FL
AR
IL
OH
NH
IL
HI